import numpy as np


# ============================================================
# DEVICE GRID
# ============================================================

Lx = 100e-9
Ly = 100e-9

Nx = 201
Ny = 201

x = np.linspace(-Lx / 2, Lx / 2, Nx)
y = np.linspace(-Ly / 2, Ly / 2, Ny)

X, Y = np.meshgrid(x, y)


# ============================================================
# ELECTROSTATIC GATE MODEL
# ============================================================

def gate_potential(
    V_left=-0.30,
    V_plunger=-0.20,
    V_right=-0.30,
    gate_width_nm=8.0,
    gate_separation_nm=25.0,
    softening_nm=5.0,
):
    """
    Calculate an effective 2D electrostatic potential
    generated by three gate regions.

    The gates are represented by finite-width Gaussian
    spatial profiles.

    This is a geometry-aware effective model and is NOT
    a solution of the full Poisson equation.
    """

    gate_width = gate_width_nm * 1e-9
    separation = gate_separation_nm * 1e-9
    softening = softening_nm * 1e-9

    # --------------------------------------------------------
    # Gate positions
    # --------------------------------------------------------

    x_left = -separation
    x_plunger = 0.0
    x_right = separation

    # --------------------------------------------------------
    # Spatial gate profiles
    # --------------------------------------------------------

    left_profile = np.exp(
        -((X - x_left) ** 2) / (2 * gate_width ** 2)
    )

    plunger_profile = np.exp(
        -((X - x_plunger) ** 2) / (2 * gate_width ** 2)
    )

    right_profile = np.exp(
        -((X - x_right) ** 2) / (2 * gate_width ** 2)
    )

    # Weak transverse decay representing finite gate influence
    transverse_profile = np.exp(
        -(Y ** 2) / (2 * (25e-9) ** 2)
    )

    left_profile *= transverse_profile
    plunger_profile *= transverse_profile
    right_profile *= transverse_profile

    # --------------------------------------------------------
    # Effective electrostatic potential
    # --------------------------------------------------------

    phi = (
        V_left * left_profile
        + V_plunger * plunger_profile
        + V_right * right_profile
    )

    # Softening prevents singular behavior and represents
    # finite vertical separation from the active layer.
    smoothing = np.exp(
        -(Y ** 2) / (2 * softening ** 2)
    )

    phi *= smoothing

    return phi


# ============================================================
# ELECTRON POTENTIAL ENERGY
# ============================================================

def electron_potential_energy(
    V_left=-0.30,
    V_plunger=-0.20,
    V_right=-0.30,
):
    """
    Convert the effective electrostatic potential phi
    into electron potential energy.

    U = -e * phi

    The returned energy is expressed in meV.
    """

    e = 1.602176634e-19

    phi = gate_potential(
        V_left=V_left,
        V_plunger=V_plunger,
        V_right=V_right,
    )

    U = -e * phi

    # Convert joules → meV
    U_meV = U / e * 1000.0

    return U_meV


# ============================================================
# SIMPLE INFORMATION FUNCTION
# ============================================================

def summarize_potential(
    V_left=-0.30,
    V_plunger=-0.20,
    V_right=-0.30,
):
    """
    Return basic numerical information about the
    calculated potential.
    """

    phi = gate_potential(
        V_left=V_left,
        V_plunger=V_plunger,
        V_right=V_right,
    )

    U_meV = electron_potential_energy(
        V_left=V_left,
        V_plunger=V_plunger,
        V_right=V_right,
    )

    return {
        "phi_min": np.min(phi),
        "phi_max": np.max(phi),
        "U_min_meV": np.min(U_meV),
        "U_max_meV": np.max(U_meV),
    }


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    summary = summarize_potential()

    print("Electrostatic model")
    print("===================")

    print(
        f"Potential range: "
        f"{summary['phi_min']:.4f} V → "
        f"{summary['phi_max']:.4f} V"
    )

    print(
        f"Electron energy range: "
        f"{summary['U_min_meV']:.4f} → "
        f"{summary['U_max_meV']:.4f} meV"
    )
